name: Scheduled Ping

on:
    schedule:
        - cron: '*/10 * * * *'
    workflow_dispatch:

jobs:
    ping_service:
        runs-on: ubuntu-latest
        steps:
            - name: Ping URL
              uses: actions/setup-node@v4 # Or any other suitable action for running a script
            - name: Execute Ping
              run: |
                  # Replace with the actual URL you want to ping
                  # For sensitive URLs, store them as repository secrets
                  curl -s -o /dev/null -w "%{http_code}" ${{ secrets.SERVICE_URL }} || exit 1
